allow kojid to start when not using ssl cert auth
kojid in koji 1.12.0 fails to start when not using ssl cert auth
Traceback (most recent call last):
   File "/usr/sbin/kojid", line 5627, in <module>
     if os.path.isfile(options.cert):
   File "/usr/lib64/python2.7/genericpath.py", line 37, in isfile
     st = os.stat(path)
 TypeError: coercing to Unicode: need string or buffer, NoneType found
if you do not have a cert option defined we should move on. so add
to the if statement a check that the option is actually defined

Signed-off-by: Dennis Gilmore <dennis@ausil.us>